apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: client-info
spec:
  #  tls:
  #  - hosts: 
  #      - web-client.tanzu.lab
  #    secretName: web-client-tls
  virtualhost:
    fqdn: web-client.tanzu.lab
  routes:
    - conditions:
      - prefix: /
      services:
        - name: client-info-web-service
          port: 80
