resources:
- crds.yaml
- namespace.yaml
- serviceaccount.yaml
- service.yaml
- deployment.yaml
- rolebinding.yaml
- role.yaml
patches:
- patch: |
    - op: replace
      path: /metadata/name
      value: grafana-operator-permissions
  target:
    kind: ClusterRole
images:
- name: ghcr.io/grafana/grafana-operator
  newName: ghcr.io/grafana/grafana-operator
  newTag: v5.18.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
