# k8s/db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque # 일반적인 용도로 사용되는 Secret 타입
data:
  # 비밀번호는 base64로 인코딩되어야 합니다.
  # 예: echo -n "your_db_password" | base64
  POSTGRES_PASSWORD: Vk13YXJlMSE= # "your_db_password"를 base64 인코딩한 값으로 대체
