# avi-controller-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: avi-controller-secret
type: Opaque
data:
  # Base64로 인코딩된 AVI 컨트롤러 사용자 이름
  # "admin" -> "YWRtaW4="
  AVI_USERNAME: YWRtaW4=
  
  # Base64로 인코딩된 AVI 컨트롤러 비밀번호
  # "VMware1!" -> "Vk13YXJlMSE="
  AVI_PASSWORD: Vk13YXJlMSE=

