version: '3.8'

services:
  web:
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - ap

  ap:
    build:
      context: ./ap
    environment:
      # 실제 AVI 컨트롤러 정보로 변경해주세요.
      AVI_CONTROLLER_IP: "tz-avi.tanzu.lab"
      AVI_USERNAME: "admin"
      AVI_PASSWORD: "VMware1!"

