version: '3.8'

services:
  avi-web:
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - avi-ap

  avi-ap:
    build:
      context: ./ap
    ports:
      - "5000:5000"
    environment:
      # 실제 AVI 컨트롤러 정보로 변경해주세요.
      AVI_CONTROLLER_IP: "vks-avi.tanzu.lab"
      AVI_USERNAME: "admin"
      AVI_PASSWORD: "VMware1!"
      POSTGRES_DB: "avi_db"
      POSTGRES_USER: "avi_user"
      POSTGRES_PASSWORD: "avi_password"
      DB_HOST: "db"
      DB_PORT: "5432"
    # db 서비스가 시작된 후 web 서비스 시작
    depends_on:
      - db

  db:
    # PostgreSQL 13 이미지 사용
    image: postgres:13
    # 환경 변수 설정
    environment:
      POSTGRES_DB: "avi_db"
      POSTGRES_USER: "avi_user"
      POSTGRES_PASSWORD: "avi_password"
    # 데이터 영속성을 위한 볼륨 설정
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

