apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: admin
      admin_password: VMware1!
# ingress tls는 https://grafana.github.io/grafana-operator/docs/examples/ingress_https/readme/ 참조
  ingress:
    spec:
      #      ingressClassName: ingressClassName을 사용할 경우, 정의합니다.
      rules:
        - host: grafana.tanzu.lab
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
  # Optionally Configure the deployment spec
  # Modifications to the securityContext and readinessProbe
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              readinessProbe:
                failureThreshold: 5
                  #          volumes:
                  #            - name: grafana-data
                  #              persistentVolumeClaim:
                  #                claimName: grafana-pvc
---
# 아래와 같은 형태로 prometheus-server 데이터소스를 추가합니다.
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
# VKS Stancard Package를 통한 prometheus-server 배포 시, service 정보
#    url: http://prometheus-server.tanzu-system-monitoring.svc.cluster.local
    url: http://prometheus-server.tanzu-system-monitoring.svc.cluster.local
    isDefault: true
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
